name: x64dbgbb

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: dxc
        required: true
        default: 4.5.2

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
            repository: x64dbg/x64dbg
            submodules: recursive
            fetch-depth: 1
      - name: Visual Studio Development Environment
        uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c # v4.0.0
        with:
          arch: x64
      - name: tocmd
        run: |
          md vin
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=OFF -DCMAKE_UNITY_BUILD_BATCH_SIZE=6 -DX64DBG_RELEASE=ON
          cmake --build build
          rd /s /q build\_deps
          # 7z a D:\arll.7z build
          7z a D:\arll.7z -m0=lzma -mx=9 -ms=4096m -mf -mfb=64 -md=32m -ms=on -ir!*lib -ir!*nja
          move D:\arll.7z vin\
        shell: cmd
      
      
      - name: Upload Windows x64
        uses: actions/upload-artifact@v7
        with:
          name: x64rel
          path: vin\arll.7z
          archive: false

 
